
  - name: install dependencies
    apt:
      update_cache: yes
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - gcc-aarch64-linux-gnu
        - python3-pip

  - name: Install docker python package
    ansible.builtin.pip:
      name: docker

  - name: Getting docker PGP Key
    run_once: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    run_once: true
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

  - name: install docker
    apt:
      update_cache: yes
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
